############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# This is the config file for EtherealCore
# If you need help, you can leave an issue on GitHub: https://github.com/EtherealDevTeam/EtherealMC/issues

############################################################
# +------------------------------------------------------+ #
# |                     EtherealCore                     | #
# +------------------------------------------------------+ #
############################################################
Spawns: