name: EtherealCore
version: '1.0-SNAPSHOT'
main: me.etherealcraft.etherealcore.EtherealCore
api-version: '1.19'
commands:
  setspawn:
    description: Set the spawn point.
    usage: /setspawn {world}
    permission: etherealcore.commands.setspawn
    permission-message: You don't have permission ' etherealcore.commands.setspawn '
  spawn:
    description: Teleport a player to the spawn point.
    usage: /spawn
    permission: etherealcore.commands.spawn
    permission-message: You don't have permission ' etherealcore.commands.spawn '
  sethome:
    description: Set's a home for the player
    usage: /sethome [homename]
    permission: etherealcore.commands.sethome
    permission-message: You don't have permission 'etherealcore.commands.sethome '
  home:
    description: Teleports a player to a home.
    usage: /home [homename]
    permission: etherealcore.commands.home
    permission-message: You don't have permission 'etherealcore.commands.home '
permissions:
  etherealcore.commands.setspawn:
    default: op
  etherealcore.commands.spawn:
    default: true
  etherealcore.commands.sethome:
    default: true